<?php
namespace App\Filament\Resources\ServiceOrderResource\Pages;
use App\Actions\ServiceOrders\CreateServiceOrder as CreateOrderAction;use App\Filament\Resources\ServiceOrderResource;use App\Models\{CustomerAddress,Product};use Filament\Resources\Pages\CreateRecord;use Illuminate\Validation\ValidationException;
class CreateServiceOrder extends CreateRecord
{
 public static $resource=ServiceOrderResource::class;
 public function updatedRecordCustomerId($customerId){$this->record['service_address']=CustomerAddress::query()->where('customer_id',$customerId)->orderByDesc('is_default')->orderBy('id')->value('address_line');}
 public function updatedRecordAdminItemProductId($productId){$product=$productId?Product::find($productId):null;$this->record['admin_item_type']='product';$this->record['admin_item_name']=$product?$product->name:null;$this->record['admin_item_unit_price']=$product?$product->selling_price:null;if(empty($this->record['admin_item_quantity']))$this->record['admin_item_quantity']=1;}
 public function create($another=false){$this->callHook('beforeValidate');$this->validate();$this->callHook('afterValidate');$data=$this->record;$productId=$data['admin_item_product_id']??null;$type=$data['admin_item_type']??'product';$name=trim((string)($data['admin_item_name']??''));$hasItem=$productId||$type==='service';if($hasItem){if($type==='product'&&!$productId)throw ValidationException::withMessages(['record.admin_item_product_id'=>'Vui lòng chọn sản phẩm.']);if($type==='service'&&$name==='')throw ValidationException::withMessages(['record.admin_item_name'=>'Vui lòng nhập tên dịch vụ.']);if((float)($data['admin_item_quantity']??1)<=0)throw ValidationException::withMessages(['record.admin_item_quantity'=>'Số lượng phải lớn hơn 0.']);$data['items']=[['product_id'=>$productId,'item_type'=>$type,'name'=>$name,'quantity'=>$data['admin_item_quantity']??1,'unit_price'=>$data['admin_item_unit_price']??0,'discount_amount'=>$data['admin_item_discount']??0,'note'=>$data['admin_item_note']??null]];}foreach(array_keys($data)as$key)if(strpos($key,'admin_')===0)unset($data[$key]);$this->record=app(CreateOrderAction::class)->execute($data);if($another){$this->fillRecord();return;}$this->redirect($this->getRedirectUrl($this->record));}
}
