<?php
namespace Tests\Feature;
use App\Actions\ServiceOrders\{AcceptAssignment,AddServiceOrderItem,AssignTechnician,CancelServiceOrder,CompleteServiceOrder,CreateServiceOrder,RecalculateServiceOrderTotals,StartServiceOrder};
use App\Domain\ServiceOrders\ServiceOrderStatusTransition;use App\Enums\{PaymentStatus,ServiceOrderStatus,ServiceOrderType,TechnicianAssignmentStatus,TechnicianWorkingStatus};use App\Models\{FilterReplacementHistory,Product,ServiceOrder,Technician,WaterPurifier};use DomainException;use Illuminate\Foundation\Testing\DatabaseTransactions;use Tests\TestCase;
class ServiceOrderManagementTest extends TestCase{use DatabaseTransactions;
private function createOrder(array $extra=[]):ServiceOrder{$p=WaterPurifier::factory()->create();return app(CreateServiceOrder::class)->execute(array_merge(['customer_id'=>$p->customer_id,'purifier_id'=>$p->id,'order_type'=>ServiceOrderType::MAINTENANCE],$extra));}
public function test_create_order_generates_code_and_initial_history(){ $o=$this->createOrder();$this->assertNotEmpty($o->order_code);$this->assertSame(ServiceOrderStatus::NEW,$o->status->value);$this->assertSame(ServiceOrderStatus::NEW,$o->statusHistories->first()->new_status);}
public function test_product_snapshot_is_immutable_after_product_price_change(){ $p=Product::factory()->create(['name'=>'Filter A','sku'=>'A1','selling_price'=>100000,'cost_price'=>50000]);$o=$this->createOrder(['items'=>[['product_id'=>$p->id,'item_type'=>'product','quantity'=>1]]]);$p->update(['name'=>'Changed','selling_price'=>999999]);$i=$o->items()->first();$this->assertSame('Filter A',$i->name);$this->assertSame('A1',$i->sku);$this->assertSame('100000.00',$i->unit_price);$this->assertSame('50000.00',$i->cost_price);}
public function test_recalculate_totals_uses_item_and_order_discounts(){ $o=$this->createOrder(['discount_amount'=>20000,'shipping_fee'=>30000]);app(AddServiceOrderItem::class)->execute($o,null,['item_type'=>'service','name'=>'A','quantity'=>2,'unit_price'=>100000,'discount_amount'=>10000]);app(AddServiceOrderItem::class)->execute($o,null,['item_type'=>'service','name'=>'B','quantity'=>1,'unit_price'=>200000,'discount_amount'=>0]);$o=app(RecalculateServiceOrderTotals::class)->execute($o);$this->assertSame('400000.00',$o->subtotal);$this->assertSame('400000.00',$o->total_amount);}
public function test_payment_status_follows_paid_amount(){ $o=$this->createOrder();app(AddServiceOrderItem::class)->execute($o,null,['item_type'=>'service','name'=>'A','quantity'=>1,'unit_price'=>200000]);$o->update(['paid_amount'=>50000]);$o=app(RecalculateServiceOrderTotals::class)->execute($o);$this->assertSame(PaymentStatus::PARTIAL,$o->payment_status->value);$o->update(['paid_amount'=>200000]);$o=app(RecalculateServiceOrderTotals::class)->execute($o);$this->assertSame(PaymentStatus::PAID,$o->payment_status->value);$o->update(['paid_amount'=>0]);$o=app(RecalculateServiceOrderTotals::class)->execute($o);$this->assertSame(PaymentStatus::UNPAID,$o->payment_status->value);}
public function test_assign_reassign_off_and_accept_rules(){ $o=$this->createOrder();$a=app(AssignTechnician::class)->execute($o,$t1=Technician::factory()->create());$this->assertSame(ServiceOrderStatus::ASSIGNED,$o->refresh()->status->value);$this->assertSame(2,$o->statusHistories()->count());$a=app(AcceptAssignment::class)->execute($a);$this->assertSame(TechnicianAssignmentStatus::ACCEPTED,$a->status->value);app(AssignTechnician::class)->execute($o,$t2=Technician::factory()->create());$this->assertSame(TechnicianAssignmentStatus::CANCELLED,$a->refresh()->status->value);$this->assertSame(1,$o->assignments()->whereIn('status',['assigned','accepted','in_progress'])->count());$this->expectException(DomainException::class);app(AssignTechnician::class)->execute($o,Technician::factory()->create(['working_status'=>TechnicianWorkingStatus::OFF]));}
public function test_start_and_complete_updates_all_aggregate_state_and_rejects_repeat(){ $o=$this->createOrder(['input_tds'=>300,'output_tds'=>20]);app(AddServiceOrderItem::class)->execute($o,null,['item_type'=>'service','name'=>'Bảo dưỡng','quantity'=>1,'unit_price'=>200000]);$t=Technician::factory()->create();$a=app(AssignTechnician::class)->execute($o,$t);$o=app(StartServiceOrder::class)->execute($o,$t);$this->assertSame(ServiceOrderStatus::IN_PROGRESS,$o->status->value);$this->assertSame(TechnicianWorkingStatus::BUSY,$t->refresh()->working_status->value);$o=app(CompleteServiceOrder::class)->execute($o);$this->assertSame(ServiceOrderStatus::COMPLETED,$o->status->value);$this->assertSame(PaymentStatus::PAID,$o->payment_status->value);$this->assertSame($o->total_amount,$o->paid_amount);$this->assertNotNull($o->completed_at);$this->assertSame(TechnicianAssignmentStatus::COMPLETED,$a->refresh()->status->value);$this->assertSame(TechnicianWorkingStatus::AVAILABLE,$t->refresh()->working_status->value);$this->assertNotNull($o->customer->refresh()->last_service_at);$this->assertNotNull($o->purifier->refresh()->last_service_at);$this->expectException(DomainException::class);app(CompleteServiceOrder::class)->execute($o);}
public function test_completing_order_deducts_aggregated_product_stock_once(){ $product=Product::factory()->create(['stock_quantity'=>10]);$o=$this->createOrder();app(AddServiceOrderItem::class)->execute($o,$product,['item_type'=>'product','quantity'=>2]);app(AddServiceOrderItem::class)->execute($o,$product,['item_type'=>'product','quantity'=>3]);$o->update(['status'=>ServiceOrderStatus::IN_PROGRESS]);app(CompleteServiceOrder::class)->execute($o);$this->assertSame('5.00',$product->refresh()->stock_quantity);$this->assertDatabaseHas('inventory_movements',['product_id'=>$product->id,'service_order_id'=>$o->id,'type'=>'service_order_completed','quantity_change'=>-5,'balance_after'=>5]);}
public function test_order_cannot_complete_when_product_stock_is_insufficient(){ $product=Product::factory()->create(['stock_quantity'=>1]);$o=$this->createOrder();app(AddServiceOrderItem::class)->execute($o,$product,['item_type'=>'product','quantity'=>2]);$o->update(['status'=>ServiceOrderStatus::IN_PROGRESS]);try{app(CompleteServiceOrder::class)->execute($o);$this->fail('Expected insufficient stock exception');}catch(DomainException $e){$this->assertStringContainsString('Không đủ tồn kho',$e->getMessage());}$this->assertSame(ServiceOrderStatus::IN_PROGRESS,$o->refresh()->status->value);$this->assertSame('1.00',$product->refresh()->stock_quantity);$this->assertSame(0,$product->inventoryMovements()->count());}
public function test_cancel_updates_assignment_and_rejects_completed_order(){ $o=$this->createOrder();$t=Technician::factory()->create();$a=app(AssignTechnician::class)->execute($o,$t);app(StartServiceOrder::class)->execute($o,$t);$o=app(CancelServiceOrder::class)->execute($o);$this->assertSame(ServiceOrderStatus::CANCELLED,$o->status->value);$this->assertSame(TechnicianAssignmentStatus::CANCELLED,$a->refresh()->status->value);$this->assertSame(TechnicianWorkingStatus::AVAILABLE,$t->refresh()->working_status->value);$done=$this->createOrder();$td=Technician::factory()->create();app(AssignTechnician::class)->execute($done,$td);app(StartServiceOrder::class)->execute($done,$td);$done=app(CompleteServiceOrder::class)->execute($done);$this->expectException(DomainException::class);app(CancelServiceOrder::class)->execute($done);}
public function test_closed_order_rejects_items_and_invalid_transition(){ $o=$this->createOrder();$o->update(['status'=>ServiceOrderStatus::COMPLETED]);try{app(AddServiceOrderItem::class)->execute($o,null,['item_type'=>'service','name'=>'x']);$this->fail('Expected exception');}catch(DomainException $e){$this->assertTrue(true);}$this->expectException(DomainException::class);app(ServiceOrderStatusTransition::class)->assertAllowed(ServiceOrderStatus::COMPLETED,ServiceOrderStatus::IN_PROGRESS);}
public function test_filter_history_links_order_and_technician(){ $o=$this->createOrder();$t=Technician::factory()->create();$h=FilterReplacementHistory::factory()->create(['purifier_id'=>$o->purifier_id,'service_order_id'=>$o->id,'technician_id'=>$t->id]);$this->assertTrue($h->serviceOrder->is($o));$this->assertTrue($h->technician->is($t));}
}
