<?php
namespace App\Filament\Resources;
use App\Enums\ServiceOrderType;use App\Filament\Resources\ServiceOrderResource\Pages;use App\Models\{Customer,Lead,WaterPurifier,Technician,Product};use Filament\Resources\Forms\Components;use Filament\Resources\Forms\Form;use Filament\Resources\Resource;use Filament\Resources\Tables\Columns;use Filament\Resources\Tables\Filter;use Filament\Resources\Tables\Table;
class ServiceOrderResource extends Resource
{
 public static $icon='heroicon-o-clipboard-list';public static $label='Đơn dịch vụ';public static $navigationLabel='Đơn dịch vụ';public static $navigationSort=20;
 public static function statusLabels(){return['new'=>'Mới','confirmed'=>'Đã xác nhận','assigned'=>'Đã phân công','on_the_way'=>'Đang di chuyển','in_progress'=>'Đang thực hiện','completed'=>'Hoàn thành','cancelled'=>'Đã hủy'];}
 public static function leadStatusLabels(){return['new'=>'Mới','contacted'=>'Đã liên hệ','qualified'=>'Tiềm năng','converted'=>'Đã chuyển đổi','lost'=>'Không thành công'];}
 public static function technicianStatusLabels(){return['available'=>'Sẵn sàng','busy'=>'Đang bận','off'=>'Nghỉ'];}
 public static function form(Form $f){$technicians=Technician::with('user')->get()->mapWithKeys(function($t){$status=(string)$t->working_status;$statusLabel=static::technicianStatusLabels()[$status]??$status;$name=optional($t->user)->name?:'Chưa có tài khoản';return[$t->id=>$t->technician_code.' — '.$name.' — '.$statusLabel];})->toArray();return$f->schema([
 Components\Select::make('customer_id')->label('Khách hàng yêu cầu dịch vụ')->options(Customer::pluck('full_name','id')->toArray())->required()->dependable(),Components\Select::make('purifier_id')->label('Sản phẩm cần thực hiện dịch vụ')->options(WaterPurifier::get()->mapWithKeys(fn($p)=>[$p->id=>$p->custom_name?:$p->serial_number?:'Sản phẩm #'.$p->id])->toArray())->placeholder('Không bắt buộc nếu chưa xác định sản phẩm'),Components\Textarea::make('service_address')->label('Địa chỉ thực hiện dịch vụ')->placeholder('Tự điền theo địa chỉ mặc định hoặc nhập địa chỉ thực hiện thực tế')->helpMessage('Có thể chỉnh lại nếu dịch vụ được thực hiện tại địa chỉ khác.')->required(),Components\Select::make('lead_id')->label('Nguồn từ khách tiềm năng')->placeholder('Không bắt buộc')->options(Lead::get()->mapWithKeys(fn($l)=>[$l->id=>($l->full_name?:'Chưa có tên').' — '.$l->phone.' — '.(static::leadStatusLabels()[$l->status]??$l->status)])->toArray()),Components\Select::make('order_type')->label('Loại dịch vụ')->options(array_combine(ServiceOrderType::values(),['Kiểm tra','Thay lõi','Sửa chữa','Lắp đặt','Bán sản phẩm','Bảo trì']))->required(),Components\DateTimePicker::make('scheduled_at')->label('Thời gian hẹn thực hiện'),Components\Textarea::make('issue_description')->label('Yêu cầu / vấn đề của khách hàng')->placeholder('Mô tả tình trạng và công việc khách hàng yêu cầu'),Components\Textarea::make('internal_note')->label('Ghi chú nội bộ của đơn')->placeholder('Chỉ dùng nội bộ, không hiển thị cho khách hàng'),Components\TextInput::make('shipping_fee')->label('Phí di chuyển / vận chuyển (VNĐ)')->numeric()->default(0),Components\TextInput::make('discount_amount')->label('Giảm giá toàn đơn (VNĐ)')->numeric()->default(0),Components\TextInput::make('paid_amount')->label('Số tiền khách đã thanh toán (VNĐ)')->numeric()->default(0)->except(Pages\CreateServiceOrder::class),Components\Placeholder::make('order_code','Mã đơn được tạo tự động sau khi lưu'),
 Components\Section::make('Phân công kỹ thuật viên', null, [Components\Select::make('admin_technician_id')->label('Kỹ thuật viên')->options($technicians),Components\Textarea::make('admin_assignment_note')->label('Ghi chú phân công')])->except(Pages\CreateServiceOrder::class),
 Components\Section::make('Sản phẩm / dịch vụ phát sinh', null, [Components\Select::make('admin_item_product_id')->label('Chọn sản phẩm')->options(Product::orderBy('name')->pluck('name','id')->toArray())->dependable()->placeholder('Không chọn nếu nhập một dịch vụ'),Components\Select::make('admin_item_type')->label('Loại nội dung')->options(['product'=>'Sản phẩm','service'=>'Dịch vụ'])->default('product'),Components\TextInput::make('admin_item_name')->label('Tên dịch vụ hoặc nội dung khác')->placeholder('Nhập khi không chọn sản phẩm'),Components\TextInput::make('admin_item_quantity')->label('Số lượng')->numeric()->default(1),Components\TextInput::make('admin_item_unit_price')->label('Đơn giá bán (VNĐ)')->numeric()->helpMessage('Tự điền theo giá bán sản phẩm và vẫn có thể chỉnh sửa.'),Components\TextInput::make('admin_item_discount')->label('Giảm giá dòng này (VNĐ)')->numeric()->default(0),Components\Textarea::make('admin_item_note')->label('Ghi chú cho sản phẩm / dịch vụ')])
 ]);}
 public static function table(Table $t){return$t->columns([Columns\Text::make('order_code')->label('Mã đơn')->primary()->searchable()->sortable(),Columns\Text::make('customer.full_name')->label('Khách hàng')->searchable(),Columns\Text::make('customer.phone')->label('Điện thoại')->searchable(),Columns\Text::make('service_address')->label('Địa chỉ thực hiện')->limit(35)->searchable(),Columns\Text::make('purifier.custom_name')->label('Sản phẩm cần dịch vụ'),Columns\Text::make('order_type')->label('Loại dịch vụ')->getValueUsing(fn($record)=>(string)$record->order_type)->options(['inspection'=>'Kiểm tra','filter_replacement'=>'Thay lõi','repair'=>'Sửa chữa','installation'=>'Lắp đặt','machine_sale'=>'Bán sản phẩm','maintenance'=>'Bảo trì']),Columns\Text::make('scheduled_at')->label('Thời gian hẹn')->dateTime('d/m/Y H:i')->sortable(),Columns\Text::make('active_technician')->label('KTV')->getValueUsing(function($o){$a=$o->assignments->first();return$a&&$a->technician?$a->technician->technician_code:null;}),Columns\Text::make('status')->label('Trạng thái')->getValueUsing(fn($record)=>(string)$record->status)->options(static::statusLabels()),Columns\Text::make('total_amount')->label('Tổng tiền')->formatUsing(fn($value)=>number_format((float)$value,0,',','.').' ₫'),Columns\Text::make('payment_status')->label('Thanh toán')->getValueUsing(fn($record)=>(string)$record->payment_status)->options(['unpaid'=>'Chưa trả','partial'=>'Một phần','paid'=>'Đã trả','refunded'=>'Hoàn tiền']),Columns\Text::make('created_at')->label('Ngày tạo')->dateTime('d/m/Y H:i')->sortable()])->filters([Filter::make('pending',fn($q)=>$q->whereIn('status',['new','confirmed','assigned','on_the_way']))->label('Chờ xử lý'),Filter::make('in_progress',fn($q)=>$q->where('status','in_progress'))->label('Đang thực hiện'),Filter::make('today',fn($q)=>$q->whereDate('scheduled_at',today()))->label('Lịch hôm nay'),Filter::make('unpaid',fn($q)=>$q->where('payment_status','unpaid'))->label('Chưa thanh toán')]);}
 public static function relations(){return[\App\Filament\Resources\ServiceOrderResource\RelationManagers\ItemsRelationManager::class];}public static function routes(){return[Pages\ListServiceOrders::routeTo('/','index'),Pages\CreateServiceOrder::routeTo('/create','create'),Pages\EditServiceOrder::routeTo('/{record}/edit','edit')];}
}
